{
    "name": "Tijara Base Pakistan",
    "summary": "Pakistan localization foundation for Tijara Suite",
    "version": "19.0.1.0.0",
    "category": "Tijara",
    "author": "Tijara Suite",
    "license": "LGPL-3",
    "depends": ["base", "contacts", "product"],
    "data": [
        "security/tijara_security.xml",
        "security/ir.model.access.csv",
        "data/pakistan_defaults.xml",
        "views/tijara_menus.xml",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
    ],
    "installable": True,
    "application": False,
}
