{
    "name": "Tijara Retail Core",
    "summary": "Retail workflows for POS, inventory, hardware, cash, returns, and exchanges",
    "version": "19.0.1.0.0",
    "category": "Tijara",
    "author": "Tijara Suite",
    "license": "LGPL-3",
    "depends": [
        "account",
        "point_of_sale",
        "purchase",
        "sale_management",
        "stock",
        "tijara_base",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/tijara_sequences.xml",
        "data/refund_reasons.xml",
        "data/pakistan_tax_defaults.xml",
        "views/tijara_retail_menus.xml",
        "views/hardware_device_views.xml",
        "views/hardware_certification_views.xml",
        "views/bulk_data_operation_views.xml",
        "views/backoffice_views.xml",
        "views/refund_exchange_views.xml",
        "views/cash_shift_views.xml",
        "views/product_template_views.xml",
    ],
    "installable": True,
    "application": True,
}
