{
    "name": "Tijara Ecommerce",
    "summary": "Website storefront, online catalog, B2B/B2C checkout, pickup/delivery, and sale order sync",
    "version": "19.0.1.0.0",
    "category": "Tijara",
    "author": "Tijara Suite",
    "license": "LGPL-3",
    "depends": [
        "website_sale",
        "sale_management",
        "stock",
        "tijara_retail_core",
        "tijara_saas_control",
        "tijara_pos_experience",
        "tijara_analytics",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ecommerce_analytics.xml",
        "data/delivery_ops_cron.xml",
        "views/ecommerce_menus.xml",
        "views/customer_address_views.xml",
        "views/delivery_event_views.xml",
        "views/delivery_provider_views.xml",
        "views/delivery_retry_views.xml",
        "views/delivery_exception_views.xml",
        "views/delivery_reconciliation_views.xml",
        "views/ecommerce_channel_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
        "views/queue_ticket_views.xml",
        "data/ecommerce_seed.xml",
    ],
    "installable": True,
    "application": False,
}
