#!/usr/bin/env python3
import argparse
import datetime as dt
import json
import shlex
import sys
from pathlib import Path


PUBLIC_REQUIRED = [
    "ODOO_DATABASE",
    "TIJARA_DISPLAY_SLUG",
    "TIJARA_KIOSK_SLUG",
    "TIJARA_CUSTOMER_DISPLAY_SLUG",
]

AUTHENTICATED_REQUIRED = [
    "ODOO_USERNAME",
    "TIJARA_POS_CONFIG_ID",
    "TIJARA_E2E_PRODUCT_ID",
    "TIJARA_E2E_PRODUCT_NAME",
    "TIJARA_E2E_PAYMENT_METHOD_ID",
    "TIJARA_E2E_PAYMENT_METHOD_NAME",
    "TIJARA_E2E_REFUND_REASON_ID",
    "TIJARA_E2E_POS_ORDER_ID",
    "TIJARA_E2E_REFUND_BARCODE",
    "TIJARA_REFUND_ACTION_URL",
    "TIJARA_REPORT_ORDER_URL",
    "TIJARA_OFFLINE_QUEUE_ACTION_URL",
]

SECRET_REQUIRED = ["ODOO_PASSWORD"]


def _utc_now():
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _truthy(value):
    return str(value or "").strip().lower() in {"1", "true", "yes", "y", "on"}


def _shell_quote(value):
    return shlex.quote(str(value or ""))


def _unquote_shell_value(value):
    text = str(value or "").strip()
    try:
        parts = shlex.split("x=%s" % text, posix=True)
    except ValueError:
        return text
    if len(parts) == 1 and parts[0].startswith("x="):
        return parts[0][2:]
    return text


def _parse_exports(path):
    exports = {}
    comments = []
    if not path.is_file():
        return exports, comments
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            comments.append(stripped)
            continue
        if not stripped.startswith("export "):
            continue
        assignment = stripped[len("export ") :].strip()
        if "=" not in assignment:
            continue
        name, value = assignment.split("=", 1)
        name = name.strip()
        if name and name.replace("_", "").isalnum():
            exports[name] = _unquote_shell_value(value)
    return exports, comments


def _required_for_scope(scope):
    required = list(PUBLIC_REQUIRED)
    if scope in {"authenticated", "full"}:
        required.extend(AUTHENTICATED_REQUIRED)
    return required


def _status_rows(command_status, required, exports, require_password, password_provided):
    rows = []
    if command_status == 0:
        rows.append(
            {
                "check": "seed_command",
                "status": "passed",
                "message": "Odoo E2E seed command completed.",
            }
        )
    else:
        rows.append(
            {
                "check": "seed_command",
                "status": "failed",
                "message": "Odoo E2E seed command exited with status %s." % command_status,
            }
        )
    for name in required:
        present = bool(str(exports.get(name) or "").strip())
        rows.append(
            {
                "check": "env:%s" % name,
                "status": "passed" if present else "failed",
                "message": (
                    "%s exported by seed." % name
                    if present
                    else "%s is required for staging browser E2E." % name
                ),
            }
        )
    if require_password:
        rows.append(
            {
                "check": "secret:ODOO_PASSWORD",
                "status": "passed" if password_provided else "failed",
                "message": (
                    "Staging E2E password was provided to the seed command; set ODOO_PASSWORD from the same secret before browser E2E."
                    if password_provided
                    else "TIJARA_E2E_PASSWORD is required to create/update the staging POS user; set ODOO_PASSWORD from the same secret before browser E2E."
                ),
            }
        )
    return rows


def _write_status(path, rows):
    lines = ["check\tstatus\tmessage"]
    for row in rows:
        lines.append("%s\t%s\t%s" % (row["check"], row["status"], row["message"]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_env_file(path, exports, base_url):
    preferred_order = PUBLIC_REQUIRED + AUTHENTICATED_REQUIRED
    ordered = []
    for name in preferred_order:
        if name in exports and name not in ordered:
            ordered.append(name)
    for name in sorted(exports):
        if name not in ordered:
            ordered.append(name)

    lines = [
        "# Generated by scripts/export_e2e_seed_evidence.py.",
        "# Non-secret values only. Load ODOO_PASSWORD from the staging secret manager.",
    ]
    if base_url:
        lines.append("export ODOO_BASE_URL=%s" % _shell_quote(base_url))
    for name in ordered:
        lines.append("export %s=%s" % (name, _shell_quote(exports[name])))
    lines.append("# export ODOO_PASSWORD=<set-from-secret-manager>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _seeded_surfaces(exports):
    return {
        "database": exports.get("ODOO_DATABASE", ""),
        "display_slug": exports.get("TIJARA_DISPLAY_SLUG", ""),
        "kiosk_slug": exports.get("TIJARA_KIOSK_SLUG", ""),
        "customer_display_slug": exports.get("TIJARA_CUSTOMER_DISPLAY_SLUG", ""),
        "pos_config_id": exports.get("TIJARA_POS_CONFIG_ID", ""),
        "product_id": exports.get("TIJARA_E2E_PRODUCT_ID", ""),
        "product_name": exports.get("TIJARA_E2E_PRODUCT_NAME", ""),
        "payment_method_id": exports.get("TIJARA_E2E_PAYMENT_METHOD_ID", ""),
        "payment_method_name": exports.get("TIJARA_E2E_PAYMENT_METHOD_NAME", ""),
        "refund_reason_id": exports.get("TIJARA_E2E_REFUND_REASON_ID", ""),
        "pos_order_id": exports.get("TIJARA_E2E_POS_ORDER_ID", ""),
        "refund_barcode_present": bool(exports.get("TIJARA_E2E_REFUND_BARCODE")),
        "refund_action_url": exports.get("TIJARA_REFUND_ACTION_URL", ""),
        "receipt_report_url": exports.get("TIJARA_REPORT_ORDER_URL", ""),
        "offline_review_url": exports.get("TIJARA_OFFLINE_QUEUE_ACTION_URL", ""),
    }


def _write_summary(path, payload, missing_variables, env_path):
    lines = [
        "# Tijara E2E Seed Evidence",
        "",
        "- Run ID: %s" % payload["run_id"],
        "- Status: %s" % payload["decision"],
        "- CI status: %s" % payload["ci_status"],
        "- Scope: %s" % payload["scope"],
        "- Database: %s" % (payload["database"] or ""),
        "- Base URL: %s" % (payload["base_url"] or ""),
        "- Started: %s" % (payload["started_at"] or ""),
        "- Finished: %s" % payload["generated_at"],
        "- Seed output: %s" % payload["seed_output_path"],
        "- Env file: %s" % env_path,
        "- Missing variables: %s" % (", ".join(missing_variables) if missing_variables else "None"),
        "",
        "## Seeded Surfaces",
        "",
    ]
    for name, value in payload["seeded_surfaces"].items():
        lines.append("- `%s`: %s" % (name, value if value not in (None, "") else "<missing>"))
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- Secret values are not copied into seed evidence.")
    lines.append("- Source `e2e-seed.env` before `make e2e-staging`, then load `ODOO_PASSWORD` from the staging secret manager.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Export Tijara staging E2E seed evidence from seed command output."
    )
    parser.add_argument("--seed-output", required=True, help="Path to seed stdout log.")
    parser.add_argument("--output", required=True, help="Directory for seed evidence.")
    parser.add_argument("--run-id", required=True, help="Seed evidence run ID.")
    parser.add_argument("--database", default="", help="Target Odoo database.")
    parser.add_argument("--base-url", default="", help="Optional staging base URL.")
    parser.add_argument(
        "--scope",
        choices=["public", "authenticated", "full"],
        default="full",
        help="Seed readiness scope.",
    )
    parser.add_argument("--started-at", default="", help="Seed run start timestamp.")
    parser.add_argument(
        "--command-status",
        type=int,
        default=0,
        help="Exit status returned by the Odoo seed command.",
    )
    parser.add_argument(
        "--password-provided",
        default="",
        help="Whether a staging POS user password was provided to the seed command.",
    )
    parser.add_argument(
        "--require-password",
        action="store_true",
        help="Require a staging POS user password for authenticated/full scope.",
    )
    args = parser.parse_args()

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    seed_output = Path(args.seed_output)
    exports, comments = _parse_exports(seed_output)
    if args.database and not exports.get("ODOO_DATABASE"):
        exports["ODOO_DATABASE"] = args.database

    required = _required_for_scope(args.scope)
    password_required = args.require_password or args.scope in {"authenticated", "full"}
    password_provided = _truthy(args.password_provided)
    rows = _status_rows(
        args.command_status,
        required,
        exports,
        password_required,
        password_provided,
    )
    missing_variables = [
        row["check"].split(":", 1)[1]
        for row in rows
        if row["check"].startswith(("env:", "secret:")) and row["status"] != "passed"
    ]

    if args.command_status != 0:
        decision = "failed"
        ci_status = "fail"
    elif missing_variables:
        decision = "blocked"
        ci_status = "fail"
    else:
        decision = "ready"
        ci_status = "pass"

    env_path = output / "e2e-seed.env"
    status_path = output / "status.tsv"
    evidence_path = output / "e2e-seed-evidence.json"
    summary_path = output / "summary.md"

    _write_env_file(env_path, exports, args.base_url)
    _write_status(status_path, rows)

    payload = {
        "run_id": args.run_id,
        "generated_at": _utc_now(),
        "started_at": args.started_at,
        "scope": args.scope,
        "database": exports.get("ODOO_DATABASE") or args.database,
        "base_url": args.base_url,
        "seed_output_path": str(seed_output),
        "env_file": str(env_path),
        "status_file": str(status_path),
        "command_status": args.command_status,
        "decision": decision,
        "ci_status": ci_status,
        "required_variables": required,
        "missing_variables": missing_variables,
        "missing_variable_count": len(missing_variables),
        "password_secret_required": password_required,
        "password_secret_provided": password_provided,
        "exports": exports,
        "seed_comments": comments[:20],
        "seeded_surfaces": _seeded_surfaces(exports),
    }
    evidence_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _write_summary(summary_path, payload, missing_variables, env_path)

    print("Tijara E2E seed evidence")
    print("run_id=%s" % args.run_id)
    print("decision=%s" % decision)
    print("ci_status=%s" % ci_status)
    print("evidence=%s" % evidence_path)
    if missing_variables:
        print("missing=%s" % ",".join(missing_variables))
    return 1 if ci_status == "fail" else 0


if __name__ == "__main__":
    raise SystemExit(main())
